# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ESSE.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(544, 474)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.inputAltura = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAltura.setObjectName("inputAltura")
        self.gridLayout.addWidget(self.inputAltura, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.btnRedimencionar = QtWidgets.QPushButton(self.centralwidget)
        self.btnRedimencionar.setObjectName("btnRedimencionar")
        self.gridLayout.addWidget(self.btnRedimencionar, 2, 4, 1, 1)
        self.inpuLargura = QtWidgets.QLineEdit(self.centralwidget)
        self.inpuLargura.setObjectName("inpuLargura")
        self.gridLayout.addWidget(self.inpuLargura, 2, 1, 1, 1)
        self.btnSalvar = QtWidgets.QPushButton(self.centralwidget)
        self.btnSalvar.setObjectName("btnSalvar")
        self.gridLayout.addWidget(self.btnSalvar, 3, 4, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 524, 367))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelimg = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelimg.setText("")
        self.labelimg.setObjectName("labelimg")
        self.gridLayout_2.addWidget(self.labelimg, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 5)
        self.botao_de_escolher_arquivo = QtWidgets.QPushButton(self.centralwidget)
        self.botao_de_escolher_arquivo.setObjectName("botao_de_escolher_arquivo")
        self.gridLayout.addWidget(self.botao_de_escolher_arquivo, 1, 4, 1, 1)
        self.input_arquivo = QtWidgets.QLineEdit(self.centralwidget)
        self.input_arquivo.setObjectName("input_arquivo")
        self.gridLayout.addWidget(self.input_arquivo, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Redimencionar imagem"))
        self.label.setText(_translate("MainWindow", "Largura"))
        self.label_2.setText(_translate("MainWindow", "Altura"))
        self.btnRedimencionar.setText(_translate("MainWindow", "Redimencionar"))
        self.btnSalvar.setText(_translate("MainWindow", "Salvar"))
        self.botao_de_escolher_arquivo.setText(_translate("MainWindow", "Escolha o arquivo"))
